include:
  - component: $CI_SERVER_FQDN/devops/verification-components/recheck@1.1

stages:
  - yosys
  - recheck
  - recheck_2

recheck-yosys:
  extends: [".recheck-yosys"]
  stage: recheck
  script:
    - recheck run smoke_yosys -e

recheck-onespin:
  extends: [".recheck-onespin"]
  stage: recheck
  script:
    - recheck run smoke_onespin -e

recheck-jasper-default:
  extends: [".recheck-jasper"]
  stage: recheck
  script:
    - recheck run smoke_jasper -e

recheck-jasper-scenario_8_bit_upperbound_255:
  extends: [".recheck-jasper"]
  dependencies: [recheck-jasper-default]
  stage: recheck_2
  script:
    - recheck run smoke_jasper -e
