include:
  - component: $CI_SERVER_FQDN/devops/verification-components/recheck@1

stages:
  - recheck

recheck-onespin:
  extends: [".recheck-onespin"]
  stage: recheck
  script:
    - recheck run smoke_onespin -e

recheck-jasper:
  extends: [".recheck-jasper"]
  stage: recheck
  script:
    - recheck run smore_jasper -e
