stages:
  - recheck

#printf "gitlab+deploy-token-8253976:gldt-NY_DAdZYHD1xbx5XUixG" | openssl base64 -A
#Z2l0bGFiK2RlcGxveS10b2tlbi04MjUzOTc2OmdsZHQtTllfREFkWllIRDF4Yng1WFVpeEc=
variables:
  DOCKER_AUTH_CONFIG: $RECHECK_IMAGE_AUTH

default:
  tags:
    - formal-verification
    - 300g

recheck:
  image: registry.gitlab.com/lubis1/eda-team/recheck/cli/recheck-onespin
  stage: recheck
  script:
    - |
      apt-get update && apt-get upgrade -y && apt-get install -y \
      curl \
      gpg \
      libx11-6 \
      libglib2.0-0 \
      git \
      ruby \
      fontconfig \
      libx11-xcb1 \
      libxcb-icccm4 \
      libxcb-image0 \
      libxcb-shm0 \
      libxcb-keysyms1 \
      libxcb-randr0 \
      libxcb-render0 \
      libxcb-render-util0 \
      libxcb-shape0 \
      libxcb-sync1 \
      libxcb-xfixes0 \
      libxcb-xinerama0 \
      libxcb-xkb1 \
      libxkbcommon0 \
      libxkbcommon-x11-0 \
      libnss3 \
      libxcomposite1 \
      libxdamage1 \
      libxfixes3 \
      libxrender1 \
      libxrandr2 \
      libxtst6 \
      libdbus-1-3 \
      libasound2t64 \
      libgl1 \
      && apt-get clean
    - recheck run smoke_onespin -e
    - recheck run smoke_jasper -e
  artifacts:
    paths:
      - logs
    when: always
