include:
  - component: $CI_SERVER_FQDN/devops/verification-components/recheck@1.1

stages:
  - yosys
  - big-eda

recheck-yosys:
  extends: [".recheck-yosys"]
  stage: yosys
  script:
    - recheck run smoke_yosys -e

recheck-onespin:
  extends: [".recheck-onespin"]
  dependencies:
    - "recheck-yosys"
  stage: big-eda
  script:
    - recheck run smoke_onespin -e

recheck-jasper-default:
  extends: [".recheck-jasper"]
  dependencies:
    - "recheck-yosys"
  stage: big-eda
  script:
    - recheck run smoke_jasper -e
