include:
  - component: $CI_SERVER_FQDN/devops/verification-components/recheck@1.2
    inputs:
      artifacts_expire_in: "1 day"

stages:
  - yosys
  - big-eda

recheck-yosys:
  extends: [".recheck-yosys"]
  stage: yosys
  script:
    - recheck run yosys -e

recheck-onespin:
  extends: [".recheck-onespin"]
  dependencies:
    - "recheck-yosys"
  stage: big-eda
  script:
    - recheck run onespin -e

recheck-jasper:
  extends: [".recheck-jasper"]
  dependencies:
    - "recheck-yosys"
  stage: big-eda
  script:
    - recheck run jasper -e
